module.exports = {
  someSidebar: {
    'Getting Started': ['Installation', 'quick_start'],
    Styles: [
      'Styles/Color',
      'Styles/Elevation',
    ],
    Components: [
      'Components/AppBar',
      'Components/Avatar',
      'Components/Badge',
      'Components/Button',
      'Components/ButtonGroup',
      'Components/Carousel',
      'Components/Checkbox',
      'Components/Icon',
      'Components/Image',
      'Components/Lightbox',
      'Components/List',
      'Components/Loader',
      {
        type: 'category',
        label: 'LiveBackground',
        items: ['Components/Cubes'],
      },
      // 'Components/Menu',
      'Components/Modal',
      // 'Components/Notify',
      'Components/Popup',
      'Components/Radio',
      'Components/Ripple',
      'Components/Scroll',
      'Components/Skeleton',
      'Components/Select',
      // 'Components/Slider',
      'Components/Switch',
      // 'Components/Tabs',
      'Components/TextField',
      'Components/Tooltip',
      'Components/TouchDriver',

    ],
    // API: [
    //   'API/AppBar',
    //   'API/Avatar',
    //   'API/AvatarGroup',
    //   'API/Badge',
    //   'API/Button',
    //   'API/ButtonBase',
    //   'API/ButtonGroup',
    //   'API/Carousel',
    //   'API/Checkbox',
    //   'API/CodeExample',
    //   'API/Cubes',
    //   'API/IconButton',
    //   'API/Lightbox',
    //   'API/List',
    //   'API/ListItem',
    //   'API/ListItemAction',
    //   'API/ListItemAvatar',
    //   'API/ListItemText',
    //   'API/Loader',
    //   'API/Menu',
    //   'API/MenuItem',
    //   'API/Modal',
    //   'API/Notify',
    //   'API/Popup',
    //   'API/PropDoc',
    //   'API/Radio',
    //   'API/Ripple',
    //   'API/Scroll',
    //   'API/Select',
    //   'API/SelectOption',
    //   'API/Skeleton',
    //   'API/Slider',
    //   'API/SvgIcon',
    //   'API/Switch',
    //   'API/SwitchBase',
    //   'API/Tabs',
    //   'API/TextField',
    //   'API/Tooltip',
    //   'API/TouchDriver',
    // ],
    // Styles: [],
    // Features: ['mdx'],
  },
};
