module.exports = {
  someSidebar: {
    'Getting Started': ['Installation'],
    Components: [
      'Components/AppBar',
      'Components/Avatar',
      'Components/Badge',
      'Components/Button',
      'Components/ButtonGroup',
      'Components/Carousel',
      'Components/Checkbox',
      'Components/Icon',
      'Components/Lightbox',
      'Components/List',
      'Components/Loader',
      // 'Components/Menu',
      'Components/Modal',
      // 'Components/Notify',
      'Components/Radio',
      'Components/Ripple',
      'Components/Scroll',
      'Components/Skeleton',
      'Components/Select',
      // 'Components/Slider',
      'Components/Switch',
      // 'Components/Tabs',
      'Components/TextField',
      'Components/Tooltip',
      'Components/TouchDriver',
    ],
    Styles: [
      'Styles/Color',
      'Styles/Elevation',
    ]
    // API: [],
    // Styles: [],
    // Features: ['mdx'],
  },
};
