name: documentation deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  checks:
    if: github.event_name != 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Test Build
        run: |
          if [ -e yarn.lock ]; then
          yarn install --frozen-lockfile
          elif [ -e package-lock.json ]; then
          npm ci
          else
          npm i
          fi
          npm run build
  gh-release:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.GH_PAGES_DEPLOY }}
      - name: Set Git config
        run: |
          git config --global user.name $GIT_USER
          git config --global user.email $USER_EMAIL
        env:
          GIT_USER: 'evg-b'
          USER_EMAIL: 'seber.bobilev@gmail.com'
          
      - name: Build Rollup packages
        run: yarn build

      - name: Release to GitHub Pages
        run: yarn workspace docsite deploy
        env:
          GIT_USER: 'evg-b'
          USE_SSH: true